<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.5" tiledversion="1.7.2" name="Minifantasy_ForgottenPlainsProps" tilewidth="8" tileheight="8" tilecount="220" columns="22">
 <image source="Minifantasy_ForgottenPlainsProps.png" width="176" height="80"/>
 <tile id="0" type="Tile"/>
 <tile id="1" type="Tile"/>
 <tile id="2" type="Tile"/>
 <tile id="3" type="Tile"/>
 <tile id="4" type="Tile"/>
 <tile id="5" type="Tile"/>
 <tile id="6" type="Tile"/>
 <tile id="7" type="Tile"/>
 <tile id="8" type="Tile"/>
 <tile id="9" type="Tile"/>
 <tile id="10" type="Tile"/>
 <tile id="11" type="Tile"/>
 <tile id="12" type="Tile"/>
 <tile id="13" type="Tile"/>
 <tile id="14" type="Tile"/>
 <tile id="15" type="Tile"/>
 <tile id="16" type="Tile"/>
 <tile id="17" type="Tile"/>
 <tile id="18" type="Tile"/>
 <tile id="19" type="Tile"/>
 <tile id="20" type="Tile"/>
 <tile id="21" type="Tile"/>
 <tile id="22" type="Tile"/>
 <tile id="23" type="Tile"/>
 <tile id="24" type="Tile"/>
 <tile id="25" type="Tile"/>
 <tile id="26" type="Tile"/>
 <tile id="27" type="Tile"/>
 <tile id="28" type="Tile"/>
 <tile id="29" type="Tile"/>
 <tile id="30" type="Tile"/>
 <tile id="31" type="Tile"/>
 <tile id="32" type="Tile"/>
 <tile id="33" type="Tile"/>
 <tile id="34" type="Tile"/>
 <tile id="35" type="Tile"/>
 <tile id="36" type="Tile"/>
 <tile id="37" type="Tile"/>
 <tile id="38" type="Tile"/>
 <tile id="39" type="Tile"/>
 <tile id="40" type="Tile"/>
 <tile id="41" type="Tile"/>
 <tile id="42" type="Tile"/>
 <tile id="43" type="Tile"/>
 <tile id="44" type="Tile"/>
 <tile id="45" type="Tile"/>
 <tile id="46" type="Tile"/>
 <tile id="47" type="Tile"/>
 <tile id="48" type="Tile"/>
 <tile id="49" type="Tile"/>
 <tile id="50" type="Tile"/>
 <tile id="51" type="Tile"/>
 <tile id="52" type="Tile"/>
 <tile id="53" type="Tile"/>
 <tile id="54" type="Tile"/>
 <tile id="55" type="Tile"/>
 <tile id="56" type="Tile"/>
 <tile id="57" type="Tile"/>
 <tile id="58" type="Tile"/>
 <tile id="59" type="Tile"/>
 <tile id="60" type="Tile"/>
 <tile id="61" type="Tile"/>
 <tile id="62" type="Tile"/>
 <tile id="63" type="Tile"/>
 <tile id="64" type="Tile"/>
 <tile id="65" type="Tile"/>
 <tile id="66" type="Tile"/>
 <tile id="67" type="Tile"/>
 <tile id="68" type="Tile"/>
 <tile id="69" type="Tile"/>
 <tile id="70" type="Tile"/>
 <tile id="71" type="Tile"/>
 <tile id="72" type="Tile"/>
 <tile id="73" type="Tile"/>
 <tile id="74" type="Tile"/>
 <tile id="75" type="Tile"/>
 <tile id="76" type="Tile"/>
 <tile id="77" type="Tile"/>
 <tile id="78" type="Tile"/>
 <tile id="79" type="Tile"/>
 <tile id="80" type="Tile"/>
 <tile id="81" type="Tile"/>
 <tile id="82" type="Tile"/>
 <tile id="83" type="Tile"/>
 <tile id="84" type="Tile"/>
 <tile id="85" type="Tile"/>
 <tile id="86" type="Tile"/>
 <tile id="87" type="Tile"/>
 <tile id="88" type="Tile"/>
 <tile id="89" type="Tile"/>
 <tile id="90" type="Tile"/>
 <tile id="91" type="Tile"/>
 <tile id="92" type="Tile"/>
 <tile id="93" type="Tile"/>
 <tile id="94" type="Tile"/>
 <tile id="95" type="Tile"/>
 <tile id="96" type="Tile"/>
 <tile id="97" type="Tile"/>
 <tile id="98" type="Tile"/>
 <tile id="99" type="Tile"/>
 <tile id="100" type="Tile"/>
 <tile id="101" type="Tile"/>
 <tile id="102" type="Tile"/>
 <tile id="103" type="Tile"/>
 <tile id="104" type="Tile"/>
 <tile id="105" type="Tile"/>
 <tile id="106" type="Tile"/>
 <tile id="107" type="Tile"/>
 <tile id="108" type="Tile"/>
 <tile id="109" type="Tile"/>
 <tile id="110" type="Tile"/>
 <tile id="111" type="Tile"/>
 <tile id="112" type="Tile"/>
 <tile id="113" type="Tile"/>
 <tile id="114" type="Tile"/>
 <tile id="115" type="Tile"/>
 <tile id="116" type="Tile"/>
 <tile id="117" type="Tile"/>
 <tile id="118" type="Tile"/>
 <tile id="119" type="Tile"/>
 <tile id="120" type="Tile"/>
 <tile id="121" type="Tile"/>
 <tile id="122" type="Tile"/>
 <tile id="123" type="Tile"/>
 <tile id="124" type="Tile"/>
 <tile id="125" type="Tile"/>
 <tile id="126" type="Tile"/>
 <tile id="127" type="Tile"/>
 <tile id="128" type="Tile"/>
 <tile id="129" type="Tile"/>
 <tile id="130" type="Tile"/>
 <tile id="131" type="Tile"/>
 <tile id="132" type="Tile"/>
 <tile id="133" type="Tile"/>
 <tile id="134" type="Tile"/>
 <tile id="135" type="Tile"/>
 <tile id="136" type="Tile"/>
 <tile id="137" type="Tile"/>
 <tile id="138" type="Tile"/>
 <tile id="139" type="Tile"/>
 <tile id="140" type="Tile"/>
 <tile id="141" type="Tile"/>
 <tile id="142" type="Tile"/>
 <tile id="143" type="Tile"/>
 <tile id="144" type="Tile"/>
 <tile id="145" type="Tile"/>
 <tile id="146" type="Tile"/>
 <tile id="147" type="Tile"/>
 <tile id="148" type="Tile"/>
 <tile id="149" type="Tile"/>
 <tile id="150" type="Tile"/>
 <tile id="151" type="Tile"/>
 <tile id="152" type="Tile"/>
 <tile id="153" type="Tile"/>
 <tile id="154" type="Tile"/>
 <tile id="155" type="Tile"/>
 <tile id="156" type="Tile"/>
 <tile id="157" type="Tile"/>
 <tile id="158" type="Tile"/>
 <tile id="159" type="Tile"/>
 <tile id="160" type="Tile"/>
 <tile id="161" type="Tile"/>
 <tile id="162" type="Tile"/>
 <tile id="163" type="Tile"/>
 <tile id="164" type="Tile"/>
 <tile id="165" type="Tile"/>
 <tile id="166" type="Tile"/>
 <tile id="167" type="Tile"/>
 <tile id="168" type="Tile"/>
 <tile id="169" type="Tile"/>
 <tile id="170" type="Tile"/>
 <tile id="171" type="Tile"/>
 <tile id="172" type="Tile"/>
 <tile id="173" type="Tile"/>
 <tile id="174" type="Tile"/>
 <tile id="175" type="Tile"/>
 <tile id="176" type="Tile"/>
 <tile id="177" type="Tile"/>
 <tile id="178" type="Tile"/>
 <tile id="179" type="Tile"/>
 <tile id="180" type="Tile"/>
 <tile id="181" type="Tile"/>
 <tile id="182" type="Tile"/>
 <tile id="183" type="Tile"/>
 <tile id="184" type="Tile"/>
 <tile id="185" type="Tile"/>
 <tile id="186" type="Tile"/>
 <tile id="187" type="Tile"/>
 <tile id="188" type="Tile"/>
 <tile id="189" type="Tile"/>
 <tile id="190" type="Tile"/>
 <tile id="191" type="Tile"/>
 <tile id="192" type="Tile"/>
 <tile id="193" type="Tile"/>
 <tile id="194" type="Tile"/>
 <tile id="195" type="Tile"/>
 <tile id="196" type="Tile"/>
 <tile id="197" type="Tile"/>
 <tile id="198" type="Tile"/>
 <tile id="199" type="Tile"/>
 <tile id="200" type="Tile"/>
 <tile id="201" type="Tile"/>
 <tile id="202" type="Tile"/>
 <tile id="203" type="Tile"/>
 <tile id="204" type="Tile"/>
 <tile id="205" type="Tile"/>
 <tile id="206" type="Tile"/>
 <tile id="207" type="Tile"/>
 <tile id="208" type="Tile"/>
 <tile id="209" type="Tile"/>
 <tile id="210" type="Tile"/>
 <tile id="211" type="Tile"/>
 <tile id="212" type="Tile"/>
 <tile id="213" type="Tile"/>
 <tile id="214" type="Tile"/>
 <tile id="215" type="Tile"/>
 <tile id="216" type="Tile"/>
 <tile id="217" type="Tile"/>
 <tile id="218" type="Tile"/>
 <tile id="219" type="Tile"/>
</tileset>
